min_sensor_dist: .05
self_see_default_padding: .01
self_see_default_scale: 1.0
self_see_links:
  - name: turret_link
    padding: 0.5
  - name: boom_link
    padding: 0.5
  - name: stick_link
    padding: 0.5
  - name: bucket_link
    padding: 0.5

  
