"""autogenerated by genpy from excavaROB_mechanism_controllers/BaseControllerState.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import excavaROB_msgs.msg
import std_msgs.msg

class BaseControllerState(genpy.Message):
  _md5sum = "0842f12a4344161afabd24de08a03a26"
  _type = "excavaROB_mechanism_controllers/BaseControllerState"
  _has_header = True #flag to mark the presence of a Header object
  _full_text = """# This represents an base controller state with reference coordinate frame and timestamp.
Header header
# Wheel joints 
string[] joint_names
# Linear and angular measured, desired and error base velocities
excavaROB_msgs/VelocityBase velocity_measured
excavaROB_msgs/VelocityBase velocity_desired
excavaROB_msgs/VelocityBase velocity_error
# Control signals
float64 control_signal_right_wheel
float64 control_signal_left_wheel



================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.secs: seconds (stamp_secs) since epoch
# * stamp.nsecs: nanoseconds since stamp_secs
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
# 0: no frame
# 1: global frame
string frame_id

================================================================================
MSG: excavaROB_msgs/VelocityBase
# This contains the linear and angular base velocity
float64 linear
float64 angular

"""
  __slots__ = ['header','joint_names','velocity_measured','velocity_desired','velocity_error','control_signal_right_wheel','control_signal_left_wheel']
  _slot_types = ['std_msgs/Header','string[]','excavaROB_msgs/VelocityBase','excavaROB_msgs/VelocityBase','excavaROB_msgs/VelocityBase','float64','float64']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,joint_names,velocity_measured,velocity_desired,velocity_error,control_signal_right_wheel,control_signal_left_wheel

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(BaseControllerState, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.joint_names is None:
        self.joint_names = []
      if self.velocity_measured is None:
        self.velocity_measured = excavaROB_msgs.msg.VelocityBase()
      if self.velocity_desired is None:
        self.velocity_desired = excavaROB_msgs.msg.VelocityBase()
      if self.velocity_error is None:
        self.velocity_error = excavaROB_msgs.msg.VelocityBase()
      if self.control_signal_right_wheel is None:
        self.control_signal_right_wheel = 0.
      if self.control_signal_left_wheel is None:
        self.control_signal_left_wheel = 0.
    else:
      self.header = std_msgs.msg.Header()
      self.joint_names = []
      self.velocity_measured = excavaROB_msgs.msg.VelocityBase()
      self.velocity_desired = excavaROB_msgs.msg.VelocityBase()
      self.velocity_error = excavaROB_msgs.msg.VelocityBase()
      self.control_signal_right_wheel = 0.
      self.control_signal_left_wheel = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_struct_3I.pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      length = len(self.joint_names)
      buff.write(_struct_I.pack(length))
      for val1 in self.joint_names:
        length = len(val1)
        if python3 or type(val1) == unicode:
          val1 = val1.encode('utf-8')
          length = len(val1)
        buff.write(struct.pack('<I%ss'%length, length, val1))
      _x = self
      buff.write(_struct_8d.pack(_x.velocity_measured.linear, _x.velocity_measured.angular, _x.velocity_desired.linear, _x.velocity_desired.angular, _x.velocity_error.linear, _x.velocity_error.angular, _x.control_signal_right_wheel, _x.control_signal_left_wheel))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.velocity_measured is None:
        self.velocity_measured = excavaROB_msgs.msg.VelocityBase()
      if self.velocity_desired is None:
        self.velocity_desired = excavaROB_msgs.msg.VelocityBase()
      if self.velocity_error is None:
        self.velocity_error = excavaROB_msgs.msg.VelocityBase()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _struct_3I.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.header.frame_id = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.joint_names = []
      for i in range(0, length):
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1 = str[start:end].decode('utf-8')
        else:
          val1 = str[start:end]
        self.joint_names.append(val1)
      _x = self
      start = end
      end += 64
      (_x.velocity_measured.linear, _x.velocity_measured.angular, _x.velocity_desired.linear, _x.velocity_desired.angular, _x.velocity_error.linear, _x.velocity_error.angular, _x.control_signal_right_wheel, _x.control_signal_left_wheel,) = _struct_8d.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_struct_3I.pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      length = len(self.joint_names)
      buff.write(_struct_I.pack(length))
      for val1 in self.joint_names:
        length = len(val1)
        if python3 or type(val1) == unicode:
          val1 = val1.encode('utf-8')
          length = len(val1)
        buff.write(struct.pack('<I%ss'%length, length, val1))
      _x = self
      buff.write(_struct_8d.pack(_x.velocity_measured.linear, _x.velocity_measured.angular, _x.velocity_desired.linear, _x.velocity_desired.angular, _x.velocity_error.linear, _x.velocity_error.angular, _x.control_signal_right_wheel, _x.control_signal_left_wheel))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.velocity_measured is None:
        self.velocity_measured = excavaROB_msgs.msg.VelocityBase()
      if self.velocity_desired is None:
        self.velocity_desired = excavaROB_msgs.msg.VelocityBase()
      if self.velocity_error is None:
        self.velocity_error = excavaROB_msgs.msg.VelocityBase()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _struct_3I.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.header.frame_id = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.joint_names = []
      for i in range(0, length):
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1 = str[start:end].decode('utf-8')
        else:
          val1 = str[start:end]
        self.joint_names.append(val1)
      _x = self
      start = end
      end += 64
      (_x.velocity_measured.linear, _x.velocity_measured.angular, _x.velocity_desired.linear, _x.velocity_desired.angular, _x.velocity_error.linear, _x.velocity_error.angular, _x.control_signal_right_wheel, _x.control_signal_left_wheel,) = _struct_8d.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_3I = struct.Struct("<3I")
_struct_8d = struct.Struct("<8d")
