/* Auto-generated by genmsg_cpp for file /home/cmastalli/ros_workspace/excavabot/excavaROB_common/excavaROB_msgs/msg/Pose.msg */
#ifndef EXCAVAROB_MSGS_MESSAGE_POSE_H
#define EXCAVAROB_MSGS_MESSAGE_POSE_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "geometry_msgs/Point.h"

namespace excavaROB_msgs
{
template <class ContainerAllocator>
struct Pose_ {
  typedef Pose_<ContainerAllocator> Type;

  Pose_()
  : position()
  , pitch(0.0)
  {
  }

  Pose_(const ContainerAllocator& _alloc)
  : position(_alloc)
  , pitch(0.0)
  {
  }

  typedef  ::geometry_msgs::Point_<ContainerAllocator>  _position_type;
   ::geometry_msgs::Point_<ContainerAllocator>  position;

  typedef double _pitch_type;
  double pitch;


  typedef boost::shared_ptr< ::excavaROB_msgs::Pose_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::excavaROB_msgs::Pose_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct Pose
typedef  ::excavaROB_msgs::Pose_<std::allocator<void> > Pose;

typedef boost::shared_ptr< ::excavaROB_msgs::Pose> PosePtr;
typedef boost::shared_ptr< ::excavaROB_msgs::Pose const> PoseConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::excavaROB_msgs::Pose_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::excavaROB_msgs::Pose_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace excavaROB_msgs

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::excavaROB_msgs::Pose_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::excavaROB_msgs::Pose_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::excavaROB_msgs::Pose_<ContainerAllocator> > {
  static const char* value() 
  {
    return "aa6401d6ee55a01633d422c108623dea";
  }

  static const char* value(const  ::excavaROB_msgs::Pose_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xaa6401d6ee55a016ULL;
  static const uint64_t static_value2 = 0x33d422c108623deaULL;
};

template<class ContainerAllocator>
struct DataType< ::excavaROB_msgs::Pose_<ContainerAllocator> > {
  static const char* value() 
  {
    return "excavaROB_msgs/Pose";
  }

  static const char* value(const  ::excavaROB_msgs::Pose_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::excavaROB_msgs::Pose_<ContainerAllocator> > {
  static const char* value() 
  {
    return "# A representation of pose in free space, composed of postion and orientation (pitch angle of the bucket). \n\
geometry_msgs/Point position\n\
float64 pitch\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
\n\
";
  }

  static const char* value(const  ::excavaROB_msgs::Pose_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::excavaROB_msgs::Pose_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::excavaROB_msgs::Pose_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.position);
    stream.next(m.pitch);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct Pose_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::excavaROB_msgs::Pose_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::excavaROB_msgs::Pose_<ContainerAllocator> & v) 
  {
    s << indent << "position: ";
s << std::endl;
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.position);
    s << indent << "pitch: ";
    Printer<double>::stream(s, indent + "  ", v.pitch);
  }
};


} // namespace message_operations
} // namespace ros

#endif // EXCAVAROB_MSGS_MESSAGE_POSE_H

