/* Auto-generated by genmsg_cpp for file /home/cmastalli/ros_workspace/excavabot/excavaROB_common/excavaROB_msgs/msg/VelocityBase.msg */
#ifndef EXCAVAROB_MSGS_MESSAGE_VELOCITYBASE_H
#define EXCAVAROB_MSGS_MESSAGE_VELOCITYBASE_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"


namespace excavaROB_msgs
{
template <class ContainerAllocator>
struct VelocityBase_ {
  typedef VelocityBase_<ContainerAllocator> Type;

  VelocityBase_()
  : linear(0.0)
  , angular(0.0)
  {
  }

  VelocityBase_(const ContainerAllocator& _alloc)
  : linear(0.0)
  , angular(0.0)
  {
  }

  typedef double _linear_type;
  double linear;

  typedef double _angular_type;
  double angular;


  typedef boost::shared_ptr< ::excavaROB_msgs::VelocityBase_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::excavaROB_msgs::VelocityBase_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct VelocityBase
typedef  ::excavaROB_msgs::VelocityBase_<std::allocator<void> > VelocityBase;

typedef boost::shared_ptr< ::excavaROB_msgs::VelocityBase> VelocityBasePtr;
typedef boost::shared_ptr< ::excavaROB_msgs::VelocityBase const> VelocityBaseConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::excavaROB_msgs::VelocityBase_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::excavaROB_msgs::VelocityBase_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace excavaROB_msgs

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::excavaROB_msgs::VelocityBase_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::excavaROB_msgs::VelocityBase_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::excavaROB_msgs::VelocityBase_<ContainerAllocator> > {
  static const char* value() 
  {
    return "144a16e4d6b53a0dbadc2e617460a173";
  }

  static const char* value(const  ::excavaROB_msgs::VelocityBase_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x144a16e4d6b53a0dULL;
  static const uint64_t static_value2 = 0xbadc2e617460a173ULL;
};

template<class ContainerAllocator>
struct DataType< ::excavaROB_msgs::VelocityBase_<ContainerAllocator> > {
  static const char* value() 
  {
    return "excavaROB_msgs/VelocityBase";
  }

  static const char* value(const  ::excavaROB_msgs::VelocityBase_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::excavaROB_msgs::VelocityBase_<ContainerAllocator> > {
  static const char* value() 
  {
    return "# This contains the linear and angular base velocity\n\
float64 linear\n\
float64 angular\n\
\n\
";
  }

  static const char* value(const  ::excavaROB_msgs::VelocityBase_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::excavaROB_msgs::VelocityBase_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::excavaROB_msgs::VelocityBase_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.linear);
    stream.next(m.angular);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct VelocityBase_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::excavaROB_msgs::VelocityBase_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::excavaROB_msgs::VelocityBase_<ContainerAllocator> & v) 
  {
    s << indent << "linear: ";
    Printer<double>::stream(s, indent + "  ", v.linear);
    s << indent << "angular: ";
    Printer<double>::stream(s, indent + "  ", v.angular);
  }
};


} // namespace message_operations
} // namespace ros

#endif // EXCAVAROB_MSGS_MESSAGE_VELOCITYBASE_H

