Header header

geometry_msgs/Point32 dump_body_p1	## Position of the corner of the dump body
geometry_msgs/Point32 dump_body_p2	## Position of the corner of the dump body
geometry_msgs/Point32 dump_body_p3	## Position of the corner of the dump body
geometry_msgs/Point32 dump_body_p4	## Position of the corner of the dump body

float32 height				## Height of the dump body
float32 width				## Width of the dump body
float32 length				## Length of the dump body

int32 LOAD=1
int32 UNLOAD=2
int32 dump_body_state
